### ISSUE TITLE
Implement target_to_bits Function

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/raito#10]
Create a function to convert a 256-bit target back to the compact `bits` representation.

Acceptance Criteria:
- Implement `target_to_bits(target: U256) -> Result<u32, Error>`
- Calculate the appropriate exponent and mantissa
- Combine exponent and mantissa into the compact format
- Ensure the result is valid and normalized
- Handle potential overflow errors

Resources:
- ZeroSync Cairo 0 code: `block_header.cairo`

**Comment by harsh-ps-2003** [comment]
Please assign this issue to me, I will add unit test soon!
