### ISSUE TITLE
[dev] Split the project into crates

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#104]
Reorganize the workspace into a set of crates:
- `raito-core` contains all core types and validation helpers
- `raito-light-client` contains main entry point and types for the light client program (that only validates block headers)
- `raito-full-client` contains main entry point and types for the full consensus client program (that validates transaction execution and utreexo proofs)
- `raito-verifier` contains main entry point and types for the recursion program that aggregates multiple light/full client porgram outputs and proofs

The project layout would look like the following:

```
/ scripts
/ crates
  / raito-core
  / raito-light-client
  / raito-full-client
  / raito-verifier
```

Rationale:
- Faster build/test times for a particular project scope (e.g. if you work on the full client you don't have to compile recursive verification stuff)
- Reduced footprint from unused parts of the code (tbh I don't know how good Cairo compiler in terms of removing dead code, but it probably makes sense to put different programs into different crates to isolate specific dependencies)
- Easier to navigate through the codebase

**Comment by maciejka** [comment]
It seems too fine grained to me. I would keep client code in a single crate, it is quite a small project in the end. Recursive verification might be another one.

**Comment by maciejka** [comment]
Can we close it for now?
