### ISSUE TITLE
[feat] Validate absolute locktime

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#106]
Extend the transaction validation helper with the following checks:
- Inputs array is not empty
- Outputs array is not empty
- Transaction can be mined (it is in its final state)

Preliminary reading:
- https://learnmeabitcoin.com/technical/transaction/locktime/
- https://learnmeabitcoin.com/technical/transaction/input/sequence/
- https://github.com/bitcoin/bitcoin/blob/master/src/consensus/tx_verify.cpp

**Comment by Jeanmichel7** [comment]
I'd like to do it when I've finished the other one

**Comment by mubarak23** [comment]
@m-kus am available to work on this, i don't have any issue am working on at the moment

**Comment by ShantelPeters** [comment]
Can i please be assigned to this issue?

**Comment by ShantelPeters** [comment]
Thank you sir @m-kus i will get straight to work

**Comment by m-kus** [comment]
How is the progress @ShantelPeters ? Do you need help with this task?

**Comment by ShantelPeters** [comment]
Hi @m-kus everything is coming along well for now 
Will let you know once I need your help .

**Comment by maciejka** [comment]
@ShantelPeters what is the status of the issue? We would like to complete all open Milestone 2 issues this week. Do need need any help?

**Comment by ShantelPeters** [comment]
So sorry sir @maciejka 
I will push a PR tomorrow sir

**Comment by maciejka** [comment]
> So sorry sir @maciejka I will push a PR tomorrow sir

?

**Comment by ShantelPeters** [comment]
Sir  I am so sorry for the delay … I encountered a few problems which is why you didn’t hear from me but I will do so soon 
I am so sorry about this

**Comment by maciejka** [comment]
@ShantelPeters @bloomingpeach provided a pr which looks like a good start. I will reassign this issue to her.

Please try to grab another issue when they are available.
