### ISSUE TITLE
Implement `compute_total_work` Function

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/raito#11]
Implement `compute_total_work` function.

Acceptance Criteria:
- implement body of the [function](https://github.com/keep-starknet-strange/raito/blob/c972cf70dd24ffc842ba5b12ca3406011107c107/src/validation.cairo#L52) based on [ZeroSync](https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/block/block_header.cairo#L322) version
- write unit tests

**Comment by olufemi-olumaiyegun** [comment]
I’ll like to work on this

**Comment by maciejka** [comment]
@olufemi-olumaiyegun I updated issue description to better reflect current repo structure. It is the same task though.

**Comment by olufemi-olumaiyegun** [comment]
wrapping this up today
