### ISSUE TITLE
[feat] Implement Hash trait for OutPoint

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#110]
We will need to calculate hashes of outpoints to update Utreexo accumulator and local cache.

Hash trait: https://github.com/starkware-libs/cairo/blob/93221753088d58f54f9a7f35a0bb338cf0bfb952/corelib/src/hash.cairo#L13

Hints:
- Rename `hash::Hash` to `Digest` to avoid confusion
- Use `Serde::serialize` to convert `Outpoint` into array of felts

Suggested deadline: 9 Sep

**Comment by ScottyDavies** [comment]
I

**Comment by m-kus** [comment]
How is the progress @ScottyDavies ? Do you need help with this task?

**Comment by ScottyDavies** [comment]
It’s going fine, I would be done soon

**Comment by maciejka** [comment]
@ScottyDavies how is it going? Do you need any help? Please let us know when do you expect to complete this issue.

**Comment by bloomingpeach** [comment]
Can I work on this issue? My PR #142 is almost done.

**Comment by od-hunter** [comment]
Can I work on this @m-kus?

**Comment by m-kus** [comment]
@bloomingpeach ideally you'd need to wait for #144 to be merged to use it for serialization

**Comment by bloomingpeach** [comment]
Hi, @m-kus, could you help me a little bit on this issue? what hash function should I use and should I introduce a new struct for the purpose of implement the `HashState` trait?

**Comment by m-kus** [comment]
@bloomingpeach `Hash` trait is agnostic to the particular hash function, it just allows to update hash state with a value of a given type. You can use Poseidon in unit tests for example.

You can find more info here: https://book.cairo-lang.org/ch11-04-hash.html#working-with-hashes

Here is an example of how `Hash` is implemented for a new type: https://github.com/starkware-libs/cairo/blob/004d2b4627b6a06a72f837957f0970cdd49d01d7/corelib/src/hash.cairo#L92

Note that you can also derive hash like `#[derive(Hash)]` as long as all members also implement it.  
Maybe it will be enough to just implement `Hash` for `@ByteArray` (see how `Serde` is implemented for `@ByteArray` in types::transaction)
