### ISSUE TITLE
[bug] Timestamp median is calculated incorrectly

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#111]
It's possible that one block could have an earlier timestamp than a block that came before it in the chain.  

Example:
- Block 156,114 = 05 Dec 2011, 06:17 (1 hour 59 minutes "before" the previous block)
- Block 156,113 = 05 Dec 2011, 08:16

So we cannot assume the list of previous timestamps is sorted.
We still want to preserve the "queue" semantics, so we cannot do sorted insert.
Thus we need to sort the items in the prev_timestamps before picking a median inside validate_timestamp helper.

Read more: https://learnmeabitcoin.com/technical/block/time/

What to do:
1. Create a unit test given the example blocks that fails for the current implementation
2. Implement simple sorting of the prev timestamps: note that in most cases the array is already sorted, and even if it's not - there are few elements to be swapped. Use the simplest algorithm possible, e.g. insertion sort.

**Comment by PavitraAgarwal21** [comment]
Can I take this issue up

**Comment by martinvibes** [comment]
hi

**Comment by m-kus** [comment]
How is the progress @martinvibes? Do you need help with this task?

**Comment by martinvibes** [comment]
@m-kus sorry for the delay will soon create a pr soon and i will reach out to you if i need your help

**Comment by maciejka** [comment]
@martinvibes what is the status of the issue? We would like to complete all Milestone 1 issues soon. Do need need any help?

You can have a look here for examples of sorting algorithms in Cairo:
https://github.com/keep-starknet-strange/alexandria/tree/main/packages/sorting

**Comment by bloomingpeach** [comment]
It seems that the assignee of this issue is inactive without progress for a week. I have created a PR to resolve the issue, kindly check it out @maciejka @m-kus

**Comment by martinvibes** [comment]
hello @maciejka @m-kus i was literally going to create a pr yesterday but my system was giving me issues which i had to fix so i will create it today
but it seems @bloomingpeach has already created a pr which is not suppose to be so.
but anyways i will create a pr today sorry for the delay
