### ISSUE TITLE
[bug] Get block script sets is_segwit field incorrectly

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#122]
Currently the script uses transaction version to determine whether it is a segwit tx, however this is incorrect.

`Transaction.is_segwit` is a combination of segwit marker and flag. In principle we could just set it to true for all blocks after the Segwit upgrade (481,824). To be confident we can check that in the transaction hex (from RPC response) the 4 byte version is followed by 0001 (segwit marker and flag).

Read more: https://learnmeabitcoin.com/technical/upgrades/segregated-witness/

**Comment by m-kus** [comment]
@lomasson do you want to follow up?

**Comment by lomasson** [comment]
@m-kus yes oc 👍
