### ISSUE TITLE
[feat] Run light client program for multiple blocks

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#125]
Create and test the following pipeline:
1. Build the program
2. Fetch next N blocks from RPC and prepare program input
3. Run program with `cairo1-run` using Sierra output and prepared arguments
4. Collect retrieved PIE
5. Go to 2

The wrapper script has to be able to validate chain from any state A to any state B (B > A).

**Comment by litmus-zhang** [comment]
@m-kus   can i work on this?
