### ISSUE TITLE
[feat] Implement `txid` function 

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/raito#13]
Create a function to calculate txid: 
https://github.com/keep-starknet-strange/raito/blob/4bf3aaba4d04f53255f32d022d3ee860ad20da8d/src/validation.cairo#L40

according to the cdescription given here:
https://learnmeabitcoin.com/technical/transaction/input/txid/

**Comment by TAdev0** [comment]
Hi @AbdelStark , may I be assigned to this issue? Thank you very much!

**Comment by maciejka** [comment]
Hi @TAdev0 , thanks for your interest. Please give us some time to organize issues.

**Comment by maciejka** [comment]
@TAdev0 please look at other issues, transaction validation is not yet ready to be assigned.

**Comment by TAdev0** [comment]
Hi @maciejka  any update regarding this issue?

**Comment by maciejka** [comment]
It is ready for development.

**Comment by captr1g** [comment]
@maciejka can I take this development/issue
