### ISSUE TITLE
[feat] Validate relative locktime (BIP-68)

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#138]
Validate transaction inputs if **relative** locktime is enabled.

Hints:
- Introduce a new `validate_input` function

Reading:
- https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki
- https://learnmeabitcoin.com/technical/transaction/input/sequence/
- https://github.com/bitcoin/bitcoin/blob/master/src/consensus/tx_verify.cpp

Suggested deadline: 9 Sep

**Comment by mubarak23** [comment]
@m-kus i will like to take this

**Comment by ShantelPeters** [comment]
Please can I work on this?

**Comment by mubarak23** [comment]
@m-kus from this function  [https://github.com/bitcoin/bitcoin/blob/d661e2b1b771abafb0b152842d775d3150032230/src/consensus/tx_verify.cpp#L39](https://github.com/bitcoin/bitcoin/blob/d661e2b1b771abafb0b152842d775d3150032230/src/consensus/tx_verify.cpp#L39)

if i understand the function above correctly,

 if a transaction has locktime, we are to determine the minimum block height and time required to satisfy the relative lock-time constraints of a transaction 

is this what the validate input function is suppose to do 

as again checking to ensure the input's locktime is respected

**Comment by m-kus** [comment]
The keyword is **relative**

Check out https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki
