### ISSUE TITLE
[feat] Implement `validate_coinbase` function

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/raito#14]
Create a function to validate  coinbase transaction of a block:
https://github.com/keep-starknet-strange/raito/blob/4bf3aaba4d04f53255f32d022d3ee860ad20da8d/src/validation.cairo#L171
ZeroSync version is here:
https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/block/block.cairo#L212
High level description:
https://learnmeabitcoin.com/technical/mining/coinbase-transaction/

**Comment by mubarak23** [comment]
I will

**Comment by maciejka** [comment]
Hi @mubarak23, thanks for your interest. Please give us some time to organize issues.

**Comment by manlikeHB** [comment]
Hi @maciejka @AbdelStark, can i work on this?
