### ISSUE TITLE
[feat] Validate coinbase outputs

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#140]
One of the coinbase transaction outputs must contain the wTXID commitment in the pkscript.
We need to validate that for all blocks starting with the Segwit upgrade.

Notes:
- wTXID commitment and witness root hash is not the same thing
- When calculating the witness root hash, the wTXID for the coinbase transaction must be set to all zeros

Reading:
- https://learnmeabitcoin.com/technical/mining/coinbase-transaction/
- https://github.com/bitcoin/bitcoin/blob/master/src/consensus/validation.h

Suggested deadline: 11 Sep

**Comment by Kaminar-i** [comment]
@m-kus can i be assigned to this

**Comment by ShantelPeters** [comment]
Hi @m-kus can i please be assigned to this issue?
