### ISSUE TITLE
[feat] Pretty print data types

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#147]
Currently it is complicated to troubleshoot errors, because debug formatting `{:?}` is not always readable (especially for `Hash`, `ByteArray`).

The alternative is to use display formatting `{}` but for that we need to implement `Display` trait for all types in the crate.
The suggested representation:
- `Hash` => hex string (reversed, as in RPC response)
- `ByteArray` => hex string
- `ChainState`, `Block`, etc => similar to Debug output, but with line breaks and indentation (roughly analogue of `{:#?}` in Rust)

Reading:
- https://book.cairo-lang.org/ch11-08-printing.html#printing-custom-data-types

**Comment by Arkachau05** [comment]
Interested . Can you Elaborate about this

**Comment by antonyjaen** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/raito---bitcoin-zk-client).

### My background and how it can be leveraged
I have been working as fullstack developer for WEB2 for 3 years, I'll like to explore WEB3 world so looks like a fun and benefit project to start with 🙂

**Comment by lomasson** [comment]
@m-kus hi can i work on it ?

**Comment by maciejka** [comment]
Hey @lomasson, any progress?

**Comment by lomasson** [comment]
Hi @maciejka , I've almost finished, just having a some little problems with the types, but nothing to worry about. Just for sure, do you want a print like "block: Block { data:.....}" or "block: data:..." ?

**Comment by maciejka** [comment]
Rather the second. @m-kus

**Comment by m-kus** [comment]
Second is more clean (yaml style) as long as it's split into multiple lines with indentation.

I'd also propose not to print full structs by default, because it's not useful anyways.

For example:

Blocks — we can print all fields except for transaction data if it's set to transactions list, which can be pretty huge.

```
header:
   version:
   time:
   bits:
   nonce:
data: <merkle root> or <number of transactions>
```

Or transactions, that might contain a lot of inputs/outputs.

```
version:
is_segwit:
inputs: <number of inputs>
outputs: <number of outputs>
lock_time:
```

Wdyt @maciejka ?

**Comment by maciejka** [comment]
Agree.
