### ISSUE TITLE
[bug] "Insufficient proof of work" error at block 757739

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#148]
Most likely a problem with transaction root calculation.

How to reproduce:
```
# remove tests/data/full_757738.json from ignore list in integration_tests.sh
scarb run integration_tests tests/data/full_757738.json
```

Requires #144 to merge

**Comment by jsandinoDev** [comment]
Hi @m-kus can I work in this?  I have experience in other projects of Keep-strange-strange like Shinigami

**Comment by m-kus** [comment]
@Jeanmichel7 are you available to debug this one?

**Comment by Jeanmichel7** [comment]
Yes
