### ISSUE TITLE
[feat] Validate (total) transaction SigOpCost

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#161]
Requires Shinigami integration.

There are hard caps (on transaction and block levels) for the usage of ECDSA signature verification codes.  
We have to implement SigOp count calculation for an individual script and then add helpers for transaction and block so that we can compute total SigOpCost.

Maybe the former is best suited to be implemented in shinigami-execution?

References:
- https://bitcoin.stackexchange.com/questions/67760/how-are-sigops-calculated
- https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L914
- https://github.com/bitcoin/bitcoin/blob/9df1906091f84d9a3a2e953a0424a88e0931ea33/src/validation.cpp#L1935

**Comment by nikhilhvr** [comment]
@m-kus  Is this issue still open if yes please assign this to me
