### ISSUE TITLE
[feat] Prevent double spending: UTXOs created and spent in the same block

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#164]
**Task**

We need to ensure that there are no two inputs within the same block that spend the same UTXO. As a side effect we will also ensure that there are no transaction duplicates.

In this task we are handling the case when UTXOs are created and spent within the same block.

**Context**
Zooming out a bit: how can we check that the outpoints we attach to the transaction inputs are legit? They are not part of the encoded transaction hence do not contribute to the merkle root. Currently all validations that use data from the outpoints are underconstrained.

The most straightforward way to address that is to maintain the so-called UTXO set:
- For every transaction output we add it to the set: if it already exists then it's an error
- For every transaction input we remove the referenced output from the set: if it does not exist then it's an error

But UTXO set can be pretty large and it is very expensive to do that in a Cairo program.  
Instead we can do the following:
- Keep only a succinct commitment to the set
- For every block provide only the necessary subset of UTXOs + inclusion proofs

So the workflow would look like the following:
- Prepare blocks extended with UTXOs (what we do already using our Python scripts)
- Generate inclusion proofs for every UTXO referenced in that block
- Program checks proofs, updates commitment

Sounds good, but there's an edge case when a certain UTXO is spent within the same block it was added.  
So the script "doesn't know" about it yet, since the UTXO set commitment was not updated to reflect that item.  
Hence we cannot generate an inclusion proof for this UTXO.

To workaround that we introduce a local "cache" that tracks such outputs:
- If we spot an output that is marked as "cached" we add item to the cache
- If we spot input that references an output marked as "cached" we try to remove item from the cache
- The cache is expected to be empty at the end of the block

Those "cache hints" are provided by the script (implemented in #141 ).

**Implementation hints**
- Use the ‘UtxoSet’ struct that already contains the cache dict
- Instantiate mutable ‘UtxoSet’ at the top level block validation and pass to the transaction validation function by reference 
- For every transaction output: construct outpoint, try to add it to the cache if marked as "cached"
- For every transaction input: calculate outpoint hash, try to remove it from the cache if marked as "cached"

**Comment by TAdev0** [comment]
@m-kus  issue can be closed
