### ISSUE TITLE
[feat] Utreexo: adding new item to the accumulator 

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#167]
**Context**

How can we check that the outpoints we attach to the transaction inputs are legit? They are not part of the encoded transaction hence do not contribute to the merkle root. Currently all validations that use data from the outpoints are underconstrained.

The most straightforward way to address that is to maintain the so-called UTXO set:
- For every transaction output we add it to the set: if it already exists then it's an error
- For every transaction input we remove the referenced output from the set: if it does not exist then it's an error

But UTXO set can be pretty large and it is very expensive to do that in a Cairo program.
Instead we can do the following:
- Keep only a succinct commitment to the set
- For every block provide only the necessary subset of UTXOs + inclusion proofs

So the workflow would look like the following:
- Prepare blocks extended with UTXOs (what we do already using our Python scripts)
- Generate inclusion proofs for every UTXO referenced in that block
- Program checks proofs, updates commitment

We will use the Utreexo accumulator to implement this scheme.

**Task**

In this task we are going to implement one of the primitives required for Utreexo integration: adding new leaf to the Merkle forest.  
In our case the leaf is Poseidon hash of an `OutPoint` item.  

**Implementation hints**

We have to add new leaves for every output in transaction.  
That means we will need to carry a mutable reference to a `UtxoSet` instance (relevant to #164 )

**References**
- https://eprint.iacr.org/2019/611.pdf (see page 7, Algorithm 1)
- https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/utxo_set/utreexo.cairo#L21

**Comment by bloomingpeach** [comment]
Thanks @m-kus for asking me, I am quite busy yesterday. Hope to work on the next available issue.
