### ISSUE TITLE
[dev] Add tests for invalid input sequence (relative locktime)

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#178]
Currently there are unit tests that cover happy path when relative locktime regulated by input sequence is respected.  
We need to also include tests for unhappy paths.

Extend `locktime.cairo` with several tests that cover scenarios both for time & height based locktimes.

Reading: https://learnmeabitcoin.com/technical/transaction/input/sequence/ (see Relative Locktime section)

**Comment by m-kus** [comment]
@mubarak23 want to follow up?

**Comment by ShantelPeters** [comment]
Hi @m-kus please can I work on this?

**Comment by mubarak23** [comment]
> @mubarak23 want to follow up?

Yes
