### ISSUE TITLE
[dev] Add tests for coinbase maturity

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#179]
Outputs of coinbase transaction cannot be spent sooner than 100 blocks.  
There is a validation rule for that implemented, but it lacks unit tests.  

Extend `validation/transaction.cairo` with at least two scenarios that cover happy and unhappy paths.

**Comment by JoE11-y** [comment]
Can I take a look at this?

**Comment by mubarak23** [comment]
@m-kus can I jump on this, 
Work on the Coinbase maturity issue before.

**Comment by m-kus** [comment]
@JoE11-y I have specified incorrect file in the issue, pls check

**Comment by JoE11-y** [comment]
@m-kus I've updated the PR, and fixed the merge issue.
