### ISSUE TITLE
[feat] Do not do segwit related computations before the actual upgrade

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#180]
We do **not** have to do the following things before `SEGWIT_BLOCK = 481_824`:
- Compute `tx_bytes_segwit`
- Compute `wtxid`
- Compute `wtxid` root and witness commitment

Update `compute_and_validate_tx_data` function to reflect that.

Hint: return `Default::default()` for the wtxid merkle root for such cases.

Reading: https://learnmeabitcoin.com/technical/transaction/wtxid/

**Comment by PavitraAgarwal21** [comment]
@m-kus Can you assigned it to me

**Comment by PavitraAgarwal21** [comment]
without any changes , during the ```scarb test``` show this error  ```test e2e:tests/data/full_169.json .../Users/pavitra/learning/raito/./scripts/data/integration_tests.sh: line 32: python: command not found```

**Comment by maciejka** [comment]
> without any changes , during the `scarb test` show this error `test e2e:tests/data/full_169.json .../Users/pavitra/learning/raito/./scripts/data/integration_tests.sh: line 32: python: command not found`

You need to install python? Then: https://github.com/keep-starknet-strange/raito?tab=readme-ov-file#build-dependencies
