### ISSUE TITLE
[feat] Check if transaction output is provably unspendable

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#185]
There are cases when we can say with 100% guarantee that a particular output cannot be spent.  
Such cases include:
- Pubkey script begins with `OP_RETURN `
- Pubkey script size is larger than the maximum allowed
- Two coinbase transactions in the past (BIP-30)

Implement three helper functions:
- `is_pubscript_unspendable(pubscript: @ByteArray)` in `validation/transaction`
- `is_bip30_unspendable(block_height: u32)` in `validation/coinbase`
- `validate_bip30_block_hash(block_height: u32, block_hash: @Digest)` in `validation/block` (ensures that these two exceptional blocks in the past has exact height/hash pair match)

Call `validate_bip30_block_hash` in `validate_and_apply`.

References:
- https://github.com/bitcoin/bitcoin/blob/a5e99669ccfe0683749ce2e2b21732a359ef62d7/src/script/script.h#L560
- https://github.com/bitcoin/bitcoin/blob/a5e99669ccfe0683749ce2e2b21732a359ef62d7/src/validation.cpp#L6310
- https://github.com/bitcoin/bitcoin/blob/a5e99669ccfe0683749ce2e2b21732a359ef62d7/src/index/coinstatsindex.cpp#L153

**Comment by mubarak23** [comment]
q

**Comment by Gerson2102** [comment]
I would like to try this sir!

**Comment by JoE11-y** [comment]
Can I take a look at this @m-kus.

**Comment by Sravya-212** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/raito---bitcoin-zk-client).

### My background and how it can be leveraged
I am Blockchain developer with 2 years of experience, I have created and deployed many decentralized projects by mainly focussing on the the Smart Contracts development and secure transactions, I have built DApps, DeFi, which are realtime projects.

### How I plan on tackling this issue
I would create a function that works in case of the following 
Pubkey script begins with OP_RETURN 
Pubkey script size is larger than the maximum allowed
Two coinbase transactions in the past (BIP-30)
and returns an event telling the user why the output cannot be spent by implementing the helper functions given into the specific paths.

**Comment by m-kus** [comment]
@Gerson2102 how is the progress on this task?

**Comment by Gerson2102** [comment]
Currently working on it. I already have the first function. The two left don't know how to do them. I was about to start asking questions about it. But did not have time recently, so maybe at night i wil start working again on it and I'll prepare questions for it.

**Comment by Sravya-212** [comment]
@Gerson2102 @m-kus can I join the task too, you don’t have to pay me or anything, I just want to contribute and learn, please let me help in this.

**Comment by m-kus** [comment]
@Sravya-212 no worries, there's gonna be more good first issues

**Comment by Jemiiah** [comment]
@m-kus would love to contribute to upcoming issues as well
