### ISSUE TITLE
[feat] create a `log!` macro

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#187]
Create a `log!` macro to improve debuggability. It should use scarb's [procedural macro](https://docs.swmansion.com/scarb/docs/reference/procedural-macro.html) to create a `log!` macro call:
```
log!(DEBUG, "validating tx: {}", txid);
```  
where arguments are: 
* logging level(one of TRACE, DEBUG), 
* log message format, 
* values to be included in the log message. 

`log!` should use `println!` under the hood to output messages.

Logging level should be controlled by scarb [features](https://docs.swmansion.com/scarb/docs/reference/conditional-compilation.html#features), i.e.: it should be possible to set current log level by setting log related feature: `log_level_trace`, `log_level_debug`. No logging should be the default.

Reading:
- https://docs.swmansion.com/scarb/docs/reference/conditional-compilation.html
- https://docs.swmansion.com/scarb/docs/reference/procedural-macro.html
- https://docs.rs/cairo-lang-macro/latest/cairo_lang_macro/

This issue requires Rust knowledge.

**Comment by ShantelPeters** [comment]
Hi @maciejka can I please work on this?

**Comment by mubarak23** [comment]
@maciejka can i take this

**Comment by maciejka** [comment]
> Hi @maciejka can I please work on this?

Do you have any Rust experience?

**Comment by mubarak23** [comment]
> > @maciejka can i take this
> > PR for issue: #178 is ready [here](https://github.com/keep-starknet-strange/raito/pull/184)
> > so am available to start working on this right away
> 
> Do you have any Rust experience?

Yes, checkout my [Github profile here ](mubarak23)

**Comment by TropicalDog17** [comment]
Hi @maciejka, can I work on this issue? I have fairly amount of experience in Rust. Thanks!

https://github.com/paradigmxyz/reth/commits/main/?author=TropicalDog17
https://github.com/near/near-sdk-rs/pull/1220

**Comment by TropicalDog17** [comment]
Hi, I've follow the scarb guild for writing procedural macros, but I can't manage to import in in Cairo code. here is the `logging` package 
![image](https://github.com/user-attachments/assets/1f34e7fe-72e8-420a-a26c-a6f6b6b1d2e9)

the file content is exactly the same as the example: https://docs.swmansion.com/scarb/docs/reference/procedural-macro.html#procedural-macro-packages-can-be-used-as-dependencies

![image](https://github.com/user-attachments/assets/6f004b22-830d-4804-8a15-cbda7c86c11b)
and I've imported to the client package, but the compiler doesn't seem to recognize the new `logging` package, and `scarb build` also fails to complete.

![image](https://github.com/user-attachments/assets/685b3cf5-eb7c-490d-b331-a76b53763794)

@maciejka @m-kus any idea about this, will appreciate any help. Thank you!

**Comment by maciejka** [comment]
@TropicalDog17 create a draft pr please, we will have a look then.
You might have a look at alexandria macros.

**Comment by TropicalDog17** [comment]
I've figured out @maciejka, but how to achieve 
> `Logging level should be controlled by scarb [features](https://docs.swmansion.com/scarb/docs/reference/conditional-compilation.html#features), i.e.: it should be possible to set current log level by setting log related feature: log_level_trace, log_level_debug. No logging should be the default.`

How to achieve the conditional compilation in Cairo, in rust I think we can get the feature value of config with `cfg!()` macro, but I can't figure how to do it in Cairo

**Comment by maciejka** [comment]
> https://docs.swmansion.com/scarb/docs/reference/conditional-compilation.html#features

Let's continue this discussion in the pr.

**Comment by maciejka** [comment]
Closing as features support in Scarb is not mature enough yet.
