### ISSUE TITLE
[bug] Block 72576 panicked with "Block header bits do not match target"

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#189]
This is one of the blocks where target is adjusted.

How to reproduce:
1. Add 72575 to regenerate_tests.sh -> light_test_cases
2. Run `scarb regenerate_tests` from packages/client folder
3. Run `scarb test`

How to troubleshoot:
- Compare computed difficulty target with the expected target
- Debug `adjust_difficulty` to understand where things go wrong
- Check against https://github.com/bitcoin/bitcoin/blob/cf0120ff024aa73a56f2975c832fda6aa8146dfa/src/pow.cpp#L13
- Also check https://github.com/bitcoin/bitcoin/blob/cf0120ff024aa73a56f2975c832fda6aa8146dfa/contrib/signet/miner#L186

After the issue is fixed:
- Generate integration tests for at least 5 more blocks where target was adjusted (see https://learnmeabitcoin.com/technical/mining/target/ -> History)
- Note that you have to specify `block height - 1` in `light_test_cases` because that's the initial height of the chain state

**Comment by PavitraAgarwal21** [comment]
@m-kus Can you assigned it to me

**Comment by Jeanmichel7** [comment]
It seems to come from the rounding of the target in the adjust_difficulty fn:
return (bits_to_target(target_to_bits(bn_new).unwrap()).unwrap(), block_time);

before that the target recalculation is correct:
BA18C78A6DFC3518A6DFC3518A6DFC3518A6DFC3518A6DFC3518A6

**Comment by Jeanmichel7** [comment]
I think my PR #174  solves the problem, i've reviewed the bits<>target algo

**Comment by m-kus** [comment]
> It seems to come from the rounding of the target in the adjust_difficulty fn: return (bits_to_target(target_to_bits(bn_new).unwrap()).unwrap(), block_time);
> 
> before that the target recalculation is correct: BA18C78A6DFC3518A6DFC3518A6DFC3518A6DFC3518A6DFC3518A6

Yup, seems like it.
I think we can have a separate method for reducing precision without doing a round-trip

**Comment by Jeanmichel7** [comment]
Yes, I tried, but in fact we redo all the target_to_bits steps with the specificity: most significant byte <0x80. Maybe factor this logic and return either the compact size format or the rounded target?
