### ISSUE TITLE
[feat] Check for transaction inputs duplicates

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#197]
**Context**

Currently, we have no protection against double spending, moreover transactions can spend outputs that were never part of the chain in the first place.

In order to address that we are introducing two mechanisms:
- Utreexo accumulator, which is a commitment to the current UTXO set
- Local cache for UTXO consumed within the same block they were created

The latter partially fixes the original problem: you cannot spend the same cached UTXO twice, because on the second attempt it won't be in the cache.

Utreexo does solve the problem with "non-existent" UTXOs: you can only reference outputs for which it is possible to generate inclusion proofs. However, nothing prevents you from referencing such output twice — the inclusion proofs are still valid! So we need additional protection mechanism.

**Task**
We need to memoize all the UTXOs we spent during the block application and check for double spending. Note that this will automatically prevent transaction duplicates.

**Implementation hints**
Currently we have `pub cache: Felt252Dict<bool>` in `UtxoSet` which stores "true" for cached yet unspent outputs.  
We can upgrade this dict to store information about both spent and unspent outputs (recall that Felt252Dict gives default values for non-existent keys, so e.g. you cannot distinct between None and false in our case). Just use `u8` instead of bool and it should be at no extra cost.

The workflow would look as follows:
- For every transaction input that references non-cached input we ensure that the outpoint is not yet spent and then add it to the dict
- For every transaction input that references cached input we ensure that **unspent** output exists and then remove it from the dict
- For every cached transaction output we ensure that it is not yet in the dict and then add it as unspent

**Tests**
Add unit tests covering happy and unhappy scenarios.

**Comment by Groxan** [comment]
Hi @m-kus, I'm available for that task
