### ISSUE TITLE
Implement `validate_target` Function

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#20]
Implement `validate_target` function.

Acceptance Criteria:
- implement body of the [function](https://github.com/keep-starknet-strange/raito/blob/c972cf70dd24ffc842ba5b12ca3406011107c107/src/validation.cairo#L37) based on [ZeroSync](https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/block/block_header.cairo#L291) version
- write unit tests

**Comment by Jeanmichel7** [comment]
Hello, can I take this one ?

**Comment by Jeanmichel7** [comment]
@maciejka for tests, would you prefer me to add a test mod at the bottom of the file with #[cfg(test)], or in a test folder at the root?

**Comment by maciejka** [comment]
For unit tests I prefer `#[cfg(test)]`.

**Comment by maciejka** [comment]
@all-contributors please add @Jeanmichel7  for <contributions>

**Comment by maciejka** [comment]
@all-contributors please add @Jeanmichel7 for #20

**Comment by maciejka** [comment]
@all-contributors please add @Jeanmichel7 for code

**Comment by maciejka** [comment]
@all-contributors please add @Jeanmichel7 for code.
