### ISSUE TITLE
[feat] Implement Utxo set flow separated from Utrexo accumulator updates

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#205]
Currently Utreexo state is part of the `UtxoSet` although it would be better to separate those two to have a cleaner design and solve some issues with batch inclusion proofs, cache integrity, and double spend prevention.

Here are the suggested changes:
- `UtxoSet` no longer includes Utreexo state
- instead it is extended with two new arrays: `leaves_to_delete` (similar to `leaves_to_add`) and `cache_keys` (to ensure all cached outputs are spent in the end)
- outpoint hashing should be refactored as a trait method
- note that outpoint hash has to include extra data — current block hash (see https://eprint.iacr.org/2019/611.pdf - hardening against collision attacks)
- we need to introduce block hash to the `Header` struct and change all scripts/tests accordingly (note that we also need to add a constraint to ensure the computed block hash equals the one we provide)

Utreexo accumulator updates / inclusion proof verification is "disabled" for now.

**Comment by m-kus** [comment]
@Groxan wanna follow up?

**Comment by ShantelPeters** [comment]
Please @m-kus can I work on this?

**Comment by Groxan** [comment]
@m-kus would be glad :)
