### ISSUE TITLE
Implement `validate_timestamp` function.

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#21]
Implement `validate_timestamp` function.

Acceptance Criteria:
- implement body of the [function](https://github.com/keep-starknet-strange/raito/blob/c972cf70dd24ffc842ba5b12ca3406011107c107/src/validation.cairo#L42) based on [ZeroSync](https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/block/block_header.cairo#L306) version
- write unit tests

**Comment by TAdev0** [comment]
hi @maciejka , may I be assigned to this issue? thanks!
