### ISSUE TITLE
[feat] Create a script to download, concat and transform previous timestamps data dump 

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#210]
# Context
As a continuation of #208 create a script to prepare previous timestamps data and media from the data dump.

Data is fetched from the Google Bitcoin Data Set in a following way:
```
select
  block_number,
  previous_timestamps,
  array(
    select * from unnest(previous_timestamps) as timestamp order by timestamp asc
  )[6] as median_timestamp
from (
  select
  bn___.number block_number,
  [
    unix_seconds(bn_11.timestamp),
    unix_seconds(bn_10.timestamp),
    unix_seconds(bn_09.timestamp),
    unix_seconds(bn_08.timestamp),
    unix_seconds(bn_07.timestamp),
    unix_seconds(bn_06.timestamp),
    unix_seconds(bn_05.timestamp),
    unix_seconds(bn_04.timestamp),
    unix_seconds(bn_03.timestamp),
    unix_seconds(bn_02.timestamp),
    unix_seconds(bn_01.timestamp)
  ] as previous_timestamps,
  from `bigquery-public-data.crypto_bitcoin.blocks` as bn___
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_01 on (bn___.number -1) = bn_01.number
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_02 on (bn_01.number -1) = bn_02.number
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_03 on (bn_02.number -1) = bn_03.number
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_04 on (bn_03.number -1) = bn_04.number
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_05 on (bn_04.number -1) = bn_05.number
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_06 on (bn_05.number -1) = bn_06.number
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_07 on (bn_06.number -1) = bn_07.number
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_08 on (bn_07.number -1) = bn_08.number
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_09 on (bn_08.number -1) = bn_09.number
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_10 on (bn_09.number -1) = bn_10.number
  join `bigquery-public-data.crypto_bitcoin.blocks` as bn_11 on (bn_10.number -1) = bn_11.number
)
```
Data is exported to a 100 files:
* first file: [000000000000.json](https://storage.cloud.google.com/shinigami-consensus/previous_outputs/000000000000.json)
* last file: [000000000099.json](https://storage.cloud.google.com/shinigami-consensus/previous_outputs/000000000099.json).

# The task
Script should:
1. download all files
2. create a mapping block number -> {previous_timestamps, median_timestamp}
3. save the mapping as a json file

# Time constraints
This task is on the critical path, it is blocking other tasks, please do not volunteer if you can't complete it in 2-3 days.

**Comment by PavitraAgarwal21** [comment]
Can I take this issue

**Comment by mubarak23** [comment]
@maciejka am available to work on this , kindly assign

**Comment by lomasson** [comment]
@maciejka i'm available if need

**Comment by PavitraAgarwal21** [comment]
@maciejka Should we create a new file for this, or should we include it in generate_data.py? Additionally, do we need to generate a separate file for each block, or should we consolidate everything into a single file that maps block_number to timestamp, median_timestamp, and the corresponding data, utilizing the data from the generated dump file?

**Comment by maciejka** [comment]
It should be a separate file.
Consolidate everything into a single file.
