### ISSUE TITLE
Implement `validate_merkle_root` function.

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#23]
Implement `validate_merkle_root` function.

Acceptance Criteria:
- implement body of the [function](https://github.com/keep-starknet-strange/raito/blob/1ee9e5d2dc437ebba8b60bdad234c5ea5b6f9a82/src/validation.cairo#L62) based on [ZeroSync](https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/block/block_header.cairo#L322) version
- write unit tests

Depends on #12

**Comment by mubarak23** [comment]
@maciejka can I work on this

**Comment by mubarak23** [comment]
For this implementation, we need to pass merkle_root value (as function parameter) for the block of transaction we are trying to validate their merkle root, such that what ever we calculate, we can compare it with what was pass

@maciejka

**Comment by maciejka** [comment]
Hi, in fact we just need to compute the merkle root. Validation would make sense if we were parsing block data. Closing as it is not necessary anymore. @mubarak23
