### ISSUE TITLE
[feat] Add retry logic to request_rpc

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#238]
Add retry logic to [request_rpc](https://github.com/keep-starknet-strange/raito/blob/43afeaf2ad4c487682f5060de5ddd5cc2f91fcd5/scripts/data/generate_data.py#L24). It should retry let's say 3 times before re raising the exception.

**Comment by mubarak23** [comment]
@maciejka can I take this

**Comment by mubarak23** [comment]
i want to add two argument to the function, 

retry and delay

where ever we are calling the function, we i will update it with the two function

**Comment by maciejka** [comment]
> i want to add two argument to the function,
> 
> retry and delay
> 
> where ever we are calling the function, we i will update it with the two function

Please declare they as constants at the top of the script.
