### ISSUE TITLE
[bug] Client fails on block 51740: Couldn't compute operand op1

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#245]
Client fails on block 51740:
```
scarb cairo-run --verbose --no-build --package client --function test --arguments-file arguments-full_51740_1.json
```
with error message:
```
Running client error: failed to run the function Caused by: Couldn't compute operand op1. Unknown value for memory cell 1:65546
```
where:
* [full_51740_1.json](https://github.com/user-attachments/files/17260313/full_51740_1.json)
* [arguments-full_51740_1.json](https://github.com/user-attachments/files/17260315/arguments-full_51740_1.json)
* [client.sierra.json](https://github.com/user-attachments/files/17264284/client.sierra.json)

same error on block 55861(small block, just 4 txs):
* [full_55861_1.json](https://github.com/user-attachments/files/17266846/full_55861_1.json)
* [arguments-full_55861_1.json](https://github.com/user-attachments/files/17266847/arguments-full_55861_1.json)

and 70183:
* [arguments-full_70183_1.json](https://github.com/user-attachments/files/17269939/arguments-full_70183_1.json)
* [full_70183_1.json](https://github.com/user-attachments/files/17269940/full_70183_1.json)

Minimal program on which the error reproduces:
```
fn main(arguments: Span<felt252>) {}
```

There seems to be some upper bound for the arguments of type array with length >= 2^15

**Comment by Jeanmichel7** [comment]
Can I do it ?

**Comment by m-kus** [comment]
A bit of context:
- The error is thrown by CairoVM `Couldn't compute operand op1. Unknown value for memory cell 1:65546`
- It might be because of pc jumps, so the first suggestion is to try run with #244 (our sha256 impl caused pc outside of program area before)
- Generally we need to isolate which instruction triggers this error in particular

**Comment by maciejka** [comment]
Possible directions of attack:
* using simple debugging techniques like adding debug messages try locate source of the problem:
    * Is it before, during or after arguments deserialization?
    * If during verification, in which part of verification logic?
    * Which subset of input trigger the problem (bisection search over the transaction set)?
* run scarb project in debugger(I had good results using RustRover from InteliJ), try to triangulate the problem looking at the cairo-vm internals

@Jeanmichel7 still ready?

**Comment by Jeanmichel7** [comment]
@maciejka Yep

**Comment by Jeanmichel7** [comment]
Sorry, but what exactly is the error?
I can't launch the client
`scarb cairo-run --verbose --no-build --package client --function test --arguments-file arguments-full_51740_1.json` 
is not supposed to work directly, is it? with 
full_51740_1.json in client/tests/data and 
arguments-full_51740.json in client/.client_cache ?
`error: unexpected argument '--arguments-file' found`

I can't launch it via client.sh either.
`scarb run client` is supposed to work?
What did I miss?

**Comment by maciejka** [comment]
It should work directly with scarb cairo-run ...

sob., 5 paź 2024, 18:58 użytkownik Jean-Michel ***@***.***>
napisał:

**Comment by Jeanmichel7** [comment]
oh already in 2.8.3! ok thanks got it

**Comment by maciejka** [comment]
When you comment out body of the [test function](https://github.com/keep-starknet-strange/raito/blob/d2dadb0a2e2d3bb7152eec18c732ff2b50a50f4b/packages/client/src/test.cairo#L37) the error still persists. Which means the cause of the problem is not in Cairo logic, we should look at the way arguments are loaded into the memory.

**Comment by m-kus** [comment]
Seems to be related https://github.com/lambdaclass/cairo-vm/issues/1728

**Comment by Jeanmichel7** [comment]
Yes, the problem doesn't come from the Cairo logic, it's the weight of the argument that's too heavy in the cairo-run management. For full block 51740 we're at 641KB, while for full block 757738 we're only at 71KB.

maybe useful:
There's a operating system's limitation, the integration test script doesn't work on block 51740:
```test tests/data/full_51740.json ... scarb/2.8.3/bin/scarb: Argument list too long```
This Operating System Limitation reveals that we've exceeded the 2MB argument limit, at least on my system 
```$> getconf ARG_MAX //2097152```
This problem can be solved by using a temporary file and use the --arguments-file option in scarb cairo-run


This raises the question of whether we're using the right way of doing things? Will it support the biggest blocks? And even several

I think that's beyond my skills, so maybe we need to look at scarb-cairo-run.
[scarb/extensions/scarb-cairo-run/src/main.rs l86](https://github.com/software-mansion/scarb/blob/eec9b4af3bdbc2ec9c391201fd530ba2b39e98ba/extensions/scarb-cairo-run/src/main.rs#L88)
```&fs::read_to_string(path.clone())```
We put all the arguments in memory at once, maybe we should stream them or use a temporary file? Not easy to test

**Comment by maciejka** [comment]
@Jeanmichel7 `Argument list too long` is fixed in #195.

I think that the problem is in the way the Cairo runner handles arguments, especially:
* https://github.com/starkware-libs/cairo/blob/737cc88d14a17e1e8b46a6d2d4061aa4b6984980/crates/cairo-lang-runner/src/lib.rs#L853
* https://github.com/starkware-libs/cairo/blob/737cc88d14a17e1e8b46a6d2d4061aa4b6984980/crates/cairo-lang-runner/src/lib.rs#L827 

Somewhere in the above code, there must be an assumption that the argument length is less than 2^15.

Let me know if you want to continue to work on this issue.

**Comment by Jeanmichel7** [comment]
@maciejka Yes, I'll try it.
It could be because of the i16 
```
/// Information about an array argument that has been added to the stack.
struct ArrayDataInfo {
    /// The offset of the pointer to the array data on the stack.
    ptr_offset : i16,
    /// The size of the array data in the stack.
    size : i16,
}
```
I'll try using a modified version of cairo to see

**Comment by maciejka** [comment]
Fixed by: https://github.com/starkware-libs/cairo/pull/6489.
