### ISSUE TITLE
[epic] Utreexo bridge node integration

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#248]
Tracking issue for the work on adapting [rustreexo accumulator](https://github.com/mit-dci/rustreexo) and [Utreexo bridge](https://github.com/Davidson-Souza/bridge) for the Bitcoin client in Cairo.

Full specification: https://hackmd.io/@m-kus/rkxVzFVCC

Milestones:
- [x] Accumulator updates
- [x] Bridge node integration

**Comment by Davidson-Souza** [comment]
@m-kus ping
