### ISSUE TITLE
[bug] Client fails on block 91722: Block hash mismatch for BIP-30

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#251]
Client:
```
scarb cairo-run --no-build --package client --function test --arguments-file arguments-full_91721_1.json
```
fails on block 91722:
```
Running client FAIL: block=91722 gas_spent=58842771 error='Block hash mismatch for BIP-30 exception at height 91722' Run panicked with [1997209042069643135709344952807065910992472029923670688473712229447419591075, 0 (''), 0 (''), 0 (''), ].
```
### Files
* [full_91721_1.json](https://github.com/user-attachments/files/17284213/full_91721_1.json)
* [arguments-full_91721_1.json](https://github.com/user-attachments/files/17284214/arguments-full_91721_1.json)

### Hint
This block is small, turn it into a [unit test](https://github.com/keep-starknet-strange/raito/tree/main/packages/client/tests/data).

**Comment by maciejka** [comment]
block 91812 has the same problem

**Comment by Jeanmichel7** [comment]
The validate_bip30_block_hash() test has hardcoded the expected hash in little endian, so we need to pass it in big endian

**Comment by m-kus** [comment]
So tldr for this case:
- There were two cases in Bitcoin history with transaction having duplicate IDs, both times it was coinbase
- The outputs of those "overriding" coinbase txs MUST NOT be spent ever

References:
- https://github.com/bitcoin/bitcoin/blob/b549cb1bd2cc4c6d7daeccdd06915bec590e90ca/src/validation.cpp#L2002
- https://bitcoinwords.github.io/where-are-the-coins#bip-30

So basically what we need to do is:
- Ensure that those two blocks are on their positions (note that this is mainnet only)
- Prevent spending outputs of coinbase transactions from those blocks

**Comment by m-kus** [comment]
@Jeanmichel7 can you do it? :)

**Comment by Jeanmichel7** [comment]
@m-kus let's go
