### ISSUE TITLE
[bug] Client fails on block: 757739: Script validation failed on tx_idx: 1, input_idx: 0: Signature DER error

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#257]
### Description
In `packages/client` command:
```
scarb test --forceall --execute_scripts  tests/data/full_757738.json 
```
fails with:
```
Script validation failed on tx_idx: 1, input_idx: 0: Signature DER error
```

**Comment by akintewe** [comment]
Hello can i be assigned this issue

**Comment by maciejka** [comment]
> Hello can i be assigned this issue

How are you going to approach it?

**Comment by akintewe** [comment]
What ill do is I will analyze transaction 1, input 0 in block 757739. I'll verify the signature's DER encoding, ensuring compliance with BIP66. I'll add granular logging to the DER decoding process, comparing our output with a reference node. I'll scrutinize our recent commits affecting signature validation, implement necessary fixes, and create a targeted test case replicating this scenario. I'll then validate the fix by re-running the full_757738.json test.

**Comment by bloomingpeach** [comment]
I tried and it seems to work, no more error. @maciejka

**Comment by akintewe** [comment]
@maciejka  can i still work on it please

**Comment by maciejka** [comment]
> I tried and it seems to work, no more error. @maciejka

The command in the description missed an `execute_scripts`. Bonus points for being alert.

**Comment by maciejka** [comment]
> @maciejka can i still work on it please

Thanks for your readiness to work. We want to consult Shinigami project first.

**Comment by akintewe** [comment]
Thank you so much

**Comment by bloomingpeach** [comment]
@maciejka 
![image](https://github.com/user-attachments/assets/a04b2838-1d7c-41a7-9d78-ae64e93abaf9)

It is most likely because witness checksig has not been implemented in Shinigami yet.

**Comment by SoarinSkySagar** [comment]
Hi @maciejka, can I work on this issue? Please give your telegram/discord username so I can propose my approach and/or discuss any other solutions
