### ISSUE TITLE
[bug] `get_timestamp_data` from `scripts/data/generate_timestamp_data.py`  does not work correctly for the first 10 blocks

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#266]
`get_timestamp_data` from `scripts/data/generate_timestamp_data.py`  does not work correctly for the first 10 blocks:
![image](https://github.com/user-attachments/assets/3483adcf-d4b7-409f-b977-04a2dae6e74b)

For the first 10 blocks get_timestamp_data should return hardcoded mainnet data in the following format: 
```
{
  "block_number": "11", 
  "epoch_start_time": "1231006505", 
  "median_timestamp": "1231472369", 
  "previous_timestamps": ["1231469665", "1231469744", "1231470173", "1231470988", "1231471428", "1231471789", "1231472369", "1231472743", "1231473279", "1231473952", "1231474360"]
}
```

**Comment by PavitraAgarwal21** [comment]
I want to take this up
