### ISSUE TITLE
[feat] create a python version of test data generating script

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#28]
Provide python version of: https://github.com/keep-starknet-strange/raito/issues/18.

It should be easy to extend it to include corresponding utxs for each tx input when we add them to the data types.

**Comment by maciejka** [comment]
@lomasson do want to continue?

**Comment by lomasson** [comment]
@maciejka yes oc

**Comment by maciejka** [comment]
@lomasson please join project tg: https://t.me/RaitoStarknet

**Comment by maciejka** [comment]
@lomasson please contact me on tg before starting to work on this issue.

**Comment by maciejka** [comment]
Hey @lomasson, how is it going? Is there any progress?

**Comment by lomasson** [comment]
Hi @maciejka, yes i've finish soon, I've realized that I was wrong about the creation of the `ByteArray` types (i'll speak in to you in tg for more details i'll would like to have your notice), and I'm doing my best to conform the script with the refactor changes made on the first `sh` / `jq` version. This is an good opportunity to request you access to the bitcoin node.

**Comment by maciejka** [comment]
Catch me on tg.
