### ISSUE TITLE
[bug] Relative locktime is not respected

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#285]
Multiple relative locktime issues:
- Relative time-based lock error on `tests/data/full_629999.json`: `Relative time-based lock time is not respected: current MTP 1589221014, outpoint MTP 1587390546, lock time 33553920 seconds`
- Relative block-based lock error on `tests/data/full_839999.json`: `Relative block-based lock time is not respected: current height 840000, outpoint height 839999, lock time 45539 blocks`

Fixups:
- `compute_and_validate_tx_data` has to use both block time and MTP (of the prev block), block time for relative locktime validation, MTP is used to initialize outpoints

Troubleshooting:
- Use https://blastapi.io/public-api/bitcoin to check what is the outpoint MTP (it should be mediantime of the block **prior** to the block containing that output) and is it the same in our test data

Hints:
- Use patched scarb to run large blocks: `cargo install --git https://github.com/m-kus/scarb --rev 514a08a97302b67a6278c0b2dbd0a0b4a57ef00d scarb-cairo-run` (also rename the original scarb-cairo-run binary to avoid conflicts)

**Comment by PavitraAgarwal21** [comment]
Can I take this up .

**Comment by maciejka** [comment]
@PavitraAgarwal21 do you need any assistance?

**Comment by PavitraAgarwal21** [comment]
The `validate_transaction function` within `compute_and_validate_tx_data` initializes the outpoint with MTP and includes a call to `validate_relative_locktime `to check relative locktime validation. The fixups seems already  implemented  .

**Comment by maciejka** [comment]
> @maciejka The `validate_transaction function` within `compute_and_validate_tx_data` initializes the outpoint with MTP and includes a call to `validate_relative_locktime `to check relative locktime validation. The fixups seems already implemented .

AFAIU `validate_transaction` should use block_time instead of MTP, so `compute_and_validate_tx_data` needs an extra  parameter `block_time`.
