### ISSUE TITLE
[bug] Leaf hash divergence

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#286]
Raito and Utreexo bridge node produce different OutPoint hashes.

How to reproduce:
- Take coninbase transaction from block 9
- Serialize into felts (see how Hash is implemented)
- Compare felt by felt with https://gist.github.com/Davidson-Souza/408a1a788783ce9f3ef91ab80edaec79

What is required:
- Determine which field is incorrect
- Fix the issue (if on our side)

New test cases can be generated using the Bridge node from this branch: https://github.com/Davidson-Souza/bridge/tree/shinigami-compat-patch-1

**Comment by baitcode** [comment]
I'd love to work on that one.
