### ISSUE TITLE
[feat] Add SIGTERM handling to `scripts/data/client.py`

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#295]
Currently it takes several Ctrl-C to stop scripts/data/client.py:
![image](https://github.com/user-attachments/assets/9a7f6d30-a624-4bd2-a9f3-d12e60d22e9e)
Add proper SIGTERM handling to the script so it behaves as expected. Make sure no unnecessary exceptions are written to the logs.

**Comment by raizo07** [comment]
Can I work on this @maciejka

**Comment by ShantelPeters** [comment]
Hi @maciejka 
Please can I be assigned to this issue

**Comment by GideonBature** [comment]
Can I work on this issue please?
