### ISSUE TITLE
[feat] Optimize the way we serialize transactions

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#298]
Currently we use [Encode](https://github.com/keep-starknet-strange/raito/blob/main/packages/consensus/src/codec.cairo) trait to serialize data before hashing. There is a performance problem in this approach as ByteArray, which is a type of the buffer we serialize to, is not the type sha256 works with. So ByteArray needs to be [converted](https://github.com/keep-starknet-strange/raito/blob/bf4b89de1bacb88bb3d1ddc89c2195fdf3047d47/packages/utils/src/sha256.cairo#L10) to `Array<u32> ` before hashing. It would be more optimal to use `Array<u32>` as a buffer type in the [codec](https://github.com/keep-starknet-strange/raito/blob/main/packages/consensus/src/codec.cairo) module.

**Comment by ShantelPeters** [comment]
Hi

**Comment by mubarak23** [comment]
@maciejka let work and

**Comment by PavitraAgarwal21** [comment]
Hey @maciejka Can I take this up, as I have worked with encode trait before

**Comment by Jeanmichel7** [comment]
Interested too

**Comment by PavitraAgarwal21** [comment]
hey @maciejka In the code,  dest.append_word_rev(val, 1 or 2 or 3);  we're appending val as either a 1-byte, 2-byte, or 3-byte value. Given that we’re trying to push these length values into an array<u32>, which uses 4 bytes (32 bits) per element, I’m wondering can we do we pad the remaining bytes with zeros when pushing into the array<u32>? or is there have anyother way . 
Also do you have any guidance on how to convert a u32 number into its little-endian form and append in the array<u32> ?

**Comment by maciejka** [comment]
> hey @maciejka In the code, dest.append_word_rev(val, 1 or 2 or 3); we're appending val as either a 1-byte, 2-byte, or 3-byte value. Given that we’re trying to push these length values into an array, which uses 4 bytes (32 bits) per element, I’m wondering can we do we pad the remaining bytes with zeros when pushing into the array? or is there have anyother way . Also do you have any guidance on how to convert a u32 number into its little-endian form and append in the array ?

You can have a look at how it is implemented ByteArray: https://github.com/starkware-libs/cairo/blob/d390b0904fd7cc7d5a0b39b61a504a25483740de/corelib/src/byte_array.cairo#L36

There is a pending_word for data that does not take full word (in ByteArray case it is felt252, in our case it is u32).

For conversion see: https://github.com/starkware-libs/cairo/blob/d390b0904fd7cc7d5a0b39b61a504a25483740de/corelib/src/byte_array.cairo#L227
