### ISSUE TITLE
Implement BlockHeader Struct

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/raito#3]
Define a `BlockHeader` struct to represent a Bitcoin block header.

Acceptance Criteria:
- Define `BlockHeader` struct with fields:
  - version: u32
  - prev_block_hash: [u8; 32]
  - merkle_root: [u8; 32]
  - timestamp: u32
  - bits: u32
  - nonce: u32
- Use appropriate types for each field
- Implement `Default` trait for `BlockHeader`

Resources:
- ZeroSync Cairo 0 code: `block_header.cairo`
- Bitcoin Block Header: https://developer.bitcoin.org/reference/block_chain.html#block-headers

**Comment by Immanuelolivia1** [comment]
I'll like to work on this issue

**Comment by maciejka** [comment]
Hi @Immanuelolivia1, thanks for your interest. Please give us some time to organize issues.

**Comment by maciejka** [comment]
Already implemented as a part of repo reorg. @Immanuelolivia1 please try to pickup another issue.
