### ISSUE TITLE
[feat] implement `compute_block_reward` function

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#36]
Computer block reward function based on [ZeroSync version](https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/block/block.cairo#L252)

**Comment by MSghais** [comment]
@maciejka I would love to work on it please!

**Comment by Gerson2102** [comment]
It is going to be more good first issues related to Cairo here? @maciejka

**Comment by maciejka** [comment]
> It is going to be more good first issues related to Cairo here? @maciejka

yes, stay tuned
