### ISSUE TITLE
[feat] Implement `fee` function

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#39]
Implement function to calculate transaction fee:
https://github.com/keep-starknet-strange/raito/blob/4bf3aaba4d04f53255f32d022d3ee860ad20da8d/src/validation.cairo#L44

ZeroSync version:
https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/transaction/transaction.cairo#L262

**Comment by stevencartavia** [comment]
Hi, can I take this?
