### ISSUE TITLE
[feat] implement `block_hash` function

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#40]
Implement `block_hash` function:
https://github.com/keep-starknet-strange/raito/blob/4bf3aaba4d04f53255f32d022d3ee860ad20da8d/src/validation.cairo#L50

Description:
https://learnmeabitcoin.com/technical/block/hash/

Don't forget about unit tests.

**Comment by Gerson2102** [comment]
Can I work in this one?

**Comment by Gerson2102** [comment]
@maciejka hello sir. I have planned to work on this in the weekend, maybe start today at night but not sure. Is that a problem for this issue?

**Comment by maciejka** [comment]
Let's say the deadline is on Monday. Ok?

**Comment by Gerson2102** [comment]
Got it, lets see what i can do.
