### ISSUE TITLE
[feat] draft block verification tests based on block data in tests/blocks

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#49]
Add two verification tests of blocks from `tests/blocks`. Add tests to `tests/blocks.cairo`.

When assigned please join project tg group.

**Comment by adrianvrj** [comment]
Hey, is this open for contribution?
If so, can I work on it?

**Comment by adrianvrj** [comment]
Hi @maciejka due to some complications I have had I will not be able to deliver this, very sorry :(

**Comment by Jeanmichel7** [comment]
@maciejka Can I take over?

**Comment by maciejka** [comment]
@Jeanmichel7 you can start from there: https://github.com/keep-starknet-strange/raito/pull/72
