### ISSUE TITLE
[feat] Try to optimize `merkle_tree::merkle_root`

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#50]
Current `merkle_root` calculation uses `u256` to represent internal hashes in the tree. While this seems very natural, it is not how things work internally. Under the hood `compute_sha256_u32_array` which accepts `Array<u32>` and returns `[u32; 8]`, so some work is wasted doing conversions. Try to optimise the process. Don't go too far though `merkle_root` function should still return `u256` but  can accept `Array<Array<u32>>`. 

Provide speedup measurements.

**Comment by Jeanmichel7** [comment]
Hello, can I try to do it ?

**Comment by TAdev0** [comment]
@maciejka

**Comment by PavitraAgarwal21** [comment]
hey can i take this issue

**Comment by Jeanmichel7** [comment]
@maciejka it seems that TAdev0 is already assigned to another issue, is it possible to assign it to me?

**Comment by maciejka** [comment]
Hey, sorry for the confusion. We discussed assigning him on the project tg
group. Maybe you can work together? @TAdev0?

pt., 9 sie 2024, 18:21 użytkownik Jean-Michel ***@***.***>
napisał:

**Comment by TAdev0** [comment]
Please go ahead @Jeanmichel7  if you d like

**Comment by Jeanmichel7** [comment]
Ah ok I should also join the Telegram group, it's up to you

**Comment by TAdev0** [comment]
ok well, lets both work on it, and we can review together once one or other has pushed a PR? what do you think?

**Comment by Jeanmichel7** [comment]
ok let's do that, I'll be available tomorrow for the review and push my draft optimizations.

**Comment by TAdev0** [comment]
hi @Jeanmichel7  , just pushed a PR which is ready for review. You can check it out and see what you can improve. There is no doubt there is room for improvements in my impl, i'll give it a second look tomorrow as well

**Comment by Jeanmichel7** [comment]
hi @TAdev0  , you've already made the changes I was thinking of making, so I continued from your code to try to improve performance by rewriting compute_sha256_u32_array to be more specific to our use case, but that only improved performance a little. 
On the big test I'm at 55468570 instead of 58159320gas.
I don't know if it's a good idea, I'm pushing a draft and I'd like your opinion.
