### ISSUE TITLE
[feat] Using `scarb get_block` generate test blocks

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#51]
Using `scarb get_block` should generate interesting bitcoin blocks. What means interesting? For sure we need blocks representing all soft forks, halvings, historial blocks like block containing pizza transaction. I assume we can start with 10 - 20 blocks.

In order to use [get_block](https://github.com/keep-starknet-strange/raito/blob/main/scripts/data/get_block.sh) you will need RPC endpoint and credentials. You will get those in pm on tg.

When assigned please join project tg group.

**Comment by TAdev0** [comment]
Hi @maciejka  can work on this during the weekend if it's available
