### ISSUE TITLE
Implement ChainState Struct

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/raito#6]
Define a `ChainState` struct to represent the current state of the blockchain.

Acceptance Criteria:
- Define `ChainState` struct with fields:
  - block_height: u32
  - total_work: u128
  - best_block_hash: [u8; 32]
  - current_target: u32
  - epoch_start_time: u32
  - prev_timestamps: [u32; 11]
- Implement `Default` trait for `ChainState`

Resources:
- ZeroSync Cairo 0 code: `block_header.cairo`

**Comment by raizo07** [comment]
Is this open for contribution?

**Comment by maciejka** [comment]
Hi @raizo07, thanks for your interest. Please give us some time to organize issues.

**Comment by maciejka** [comment]
Already implemented as a part of repo reorg. @raizo07 please try to pickup another issue.
