### ISSUE TITLE
[bug] List of previous block timestamps is updated incorrectly

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#68]
Current behavior: oldest timestamp is removed from the beginning of the array, new timestamp also added to the beginning of the array.

Expected behavior: oldest timestamp is removed from the beginning of the array, new timestamp added to the end.

Notes: in Zerosync implementation they use reversed order i.e. oldest timestamps are in the end of the array while the recent ones in the beginning. However for validation purposes (more specifically for computing the median) it does not matter.

**Comment by TAdev0** [comment]
@m-kus
