### ISSUE TITLE
Implement `next_prev_timestamps` Function

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/raito#7]
Implement `next_prev_timestamps` function.

Acceptance Criteria:
- implement body of the [function](https://github.com/keep-starknet-strange/raito/blob/c972cf70dd24ffc842ba5b12ca3406011107c107/src/validation.cairo#L47) based on [ZeroSync](https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/block/block_header.cairo#L347) version
- write unit tests

**Comment by olufemi-olumaiyegun** [comment]
I’ll like to work on this

**Comment by maciejka** [comment]
@olufemi-olumaiyegun the issue description has been updated. Assigning you as the scope is smaller now.

**Comment by olufemi-olumaiyegun** [comment]
wrapping this up tomorrow

**Comment by maciejka** [comment]
Any progress?

**Comment by TAdev0** [comment]
@olufemi-olumaiyegun  if you are finally unavailable i can push a PR for this today
