### ISSUE TITLE
[dev] change type of all fields holding hashes to Hash

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/raito#71]
All txid, best_block_hash should be of type `Hash`

**Comment by coxmars** [comment]
Hi @maciejka I would like to help with this one sir 🫡

**Comment by maciejka** [comment]
It is a continuation of another issue, it makes sense to assign it to a person that already worked on this subject.

**Comment by maciejka** [comment]
There will be other issues. Don't worry.

**Comment by TAdev0** [comment]
@maciejka
