### ISSUE TITLE
[feat] implement `Encode` trait for structs that need it

### ISSUE THREAD

**Issue by TAdev0** [keep-starknet-strange/raito#81]
#77  introduced `Encode` trait and implemented it for `Span<T>` and `ByteArray` types. We also need to implement it for some structs that need it

**Comment by PavitraAgarwal21** [comment]
Can I take this issue

**Comment by lana-shanghai** [comment]
Assigned @PavitraAgarwal21 
You have to implement `Encode` for `Transaction`, `TxIn`, `TxOut`, and `OutPoint` pls feel free to ask any questions!

**Comment by PavitraAgarwal21** [comment]
can we use the alexandria library

**Comment by m-kus** [comment]
> @lana-shanghai can we use the alexandria library

Which method do you need from Alexandria?

**Comment by lana-shanghai** [comment]
> @lana-shanghai can we use the alexandria library

Why do you need it? For structs you need custom encodings. I would take a look at [how it is done in pure Rust](https://docs.rs/compact-encoding/latest/compact_encoding/#custom). You can reuse Alexandria of course, but in this context it doesn't have what you need imo

**Comment by PavitraAgarwal21** [comment]
I'm exploring an alternative approach to implementing compact encoding, which typically relies on bit-shifting operations like shr and shl

**Comment by m-kus** [comment]
> I'm exploring an alternative approach to implementing compact encoding, which typically relies on bit-shifting operations like shr and shl

There are `shl` and `shr` in utils

**Comment by PavitraAgarwal21** [comment]
Hey I couldn't find a to_little_endian function. Can we create one to simplify compact size encoding and transaction serialization?

**Comment by m-kus** [comment]
> Hey I couldn't find a to_little_endian function. Can we create one to simplify compact size encoding and transaction serialization?

You can use `append_word_rev` to extend output buffer with a LE integer

**Comment by TAdev0** [comment]
hi @PavitraAgarwal21 , whats up with this issue?

**Comment by PavitraAgarwal21** [comment]
able to make the draft PR soon

**Comment by m-kus** [comment]
@PavitraAgarwal21 we need to merge this, I'm reassigning the task (your contribution still counts though it's partial)

**Comment by Jeanmichel7** [comment]
@m-kus
