### ISSUE TITLE
Implement bits_to_target Function

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/raito#9]
Create a function to convert the compact `bits` representation to the full 256-bit target.

Acceptance Criteria:
- Implement `bits_to_target(bits: u32) -> Result<U256, Error>`
- Extract exponent and mantissa from `bits`
- Calculate the full target value
- Ensure the target doesn't exceed the maximum allowed value
- Handle potential overflow errors

Resources:
- ZeroSync Cairo 0 code: `block_header.cairo`

**Comment by maciejka** [comment]
Welcome and thanks for contribution.
Please add unit tests. And add comment to the issue #15 so I can assign you.

**Comment by harsh-ps-2003** [comment]
Kindly assign this issue, I will add the unit test soon!

**Comment by harsh-ps-2003** [comment]
I am not associated to OnlyDust!
