### ISSUE TITLE
[feat] Try to run main with arguments using scarb

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#96]
Scarb should be able to run arbitrary functions with args but it's not clear whether it supports any type of args.
https://docs.swmansion.com/scarb/docs/extensions/cairo-run.html#program-arguments

In order to check if we can rely on that feature, we need:
1. Introduce ProgramInput type that will contain a single (for now) ChainState and Block
2. Modify `main` function to accept argument of type ProgramInput and invoke validation procedure
3. Prepare test data using a modified jq filter (or Python script)
4. Try to run e2e scenario with Scarb

**Comment by TAdev0** [comment]
here i am @m-kus
